perf: replace simple object as key-value storage to map (#2018)
nestjs/throttler pull request #2023
Opened 2024-06-24 11:58 UTC by melonges

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: #2018 

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2024-06-24 15:34 UTC, micalevisk commented on src/throttler.service.ts
>    }
we can drop this method in favor of accessing `this._map` directly inside this class

2024-06-24 15:34 UTC, micalevisk commented on src/throttler.service.ts
> +  private _map: Map<string, ThrottlerStorageOptions> = new Map();
I think we should keep the old name `_storage` instead of rebranding it. The fact that we are using a Map is just a implementation detail

2024-06-24 15:36 UTC, micalevisk commented on src/throttler.service.ts
> +    return Object.fromEntries(this.map);
I guess we can have a TODO note here like this:

```
// TODO(v6): change Record to Map, for performance sake
```

2024-06-24 15:36 UTC, micalevisk requested changes
please see if the suggestions I've made do makes sense

2024-06-24 18:05 UTC, melonges commented
So, need to decide which way we're gonna go.
If we don't want to change the `storage()` interface, we have two choices:
1. When accessing storage, we must transform Map to object with saving the state of storage.
2. Return Map with the object interface without saving data access to Map.

The first approach is slower because of the transformation but with the possibility of returning the data to the public API, but the second approach will be faster. If a new release with the change storage interface is coming soon, then can sacrifice performance for this time.

2024-07-08 20:38 UTC, jmcdo29 commented
I've got a PR for v6 ready, if you want to set this to the `Map` return and add a changeset with the breaking changes explained I'll get them released at the same time

2024-07-08 21:53 UTC, melonges commented
> I've got a PR for v6 ready, if you want to set this to the `Map` return and add a changeset with the breaking changes explained I'll get them released at the same time

Got it. I'll do it soon

2024-07-11 21:26 UTC, merged